version: '3.9'
services:
  # nautobot:
  prometheus:
    image: prom/prometheus:v2.30.1
    ports:
      - 9090:9090
    networks:
      - mystack
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/data
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path:/data'
      - '--storage.tsdb.retention.time:30d'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.1.5
    ports:
      - 3000:3000
    networks:
      - mystack
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  # telegraf:
  # mongodb:
  # elasticsearch:
  # graylog:

networks:
  mystack:

volumes:
  # nautobot:
  prometheus-data:
  grafana-data:
  # telegraf:
  # mongodb:
  # elasticsearch:
  # graylog:

