global:
  scrape_interval: 15s
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - 'alert.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['192.168.0.200:9100']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'gnmi'
    scrape_interval: 30s
    static_configs:
      - targets:
        - '192.168.0.200:9001'